<?php

namespace Database\Seeders;

use Carbon\Carbon;
use App\Models\User;
use App\Models\People;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
   
class PropertiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('properties')->insert([
            
        [
            'location_id' => 1,
            'property_name' => 'Sea View',
            'near_beach' => 1,
            'accepts_pets' => 1,
            'sleeps' => 4,
            'beds' => 2,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 2,
            'property_name' => 'Cosey',
            'near_beach' => 0,
            'accepts_pets' => 0,
            'sleeps' => 6,
            'beds' => 4,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 3,
            'property_name' => 'The Retreat',
            'near_beach' => 1,
            'accepts_pets' => 0,
            'sleeps' => 2,
            'beds' => 1,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 4,
            'property_name' => 'Coach House',
            'near_beach' => 0,
            'accepts_pets' => 1,
            'sleeps' => 2,
            'beds' => 3,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 5,
            'property_name' => 'Beach Cottage',
            'near_beach' => 1,
            'accepts_pets' => 0,
            'sleeps' => 4,
            'beds' => 5,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 4,
            'property_name' => 'Yellow Cottage',
            'near_beach' => 1,
            'accepts_pets' => 0,
            'sleeps' => 3,
            'beds' => 3,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 3,
            'property_name' => 'Green House',
            'near_beach' => 1,
            'accepts_pets' => 1,
            'sleeps' => 2,
            'beds' => 2,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 2,
            'property_name' => 'Blue Building',
            'near_beach' => 0,
            'accepts_pets' => 1,
            'sleeps' => 5,
            'beds' => 6,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 4,
            'property_name' => 'Orange Shack',
            'near_beach' => 0,
            'accepts_pets' => 1,
            'sleeps' => 2,
            'beds' => 3,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 3,
            'property_name' => 'Pink Cottage',
            'near_beach' => 1,
            'accepts_pets' => 0,
            'sleeps' => 4,
            'beds' => 5,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 1,
            'property_name' => 'Purple Room',
            'near_beach' => 0,
            'accepts_pets' => 0,
            'sleeps' => 5,
            'beds' => 5,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 2,
            'property_name' => 'Red Floor',
            'near_beach' => 1,
            'accepts_pets' => 1,
            'sleeps' => 2,
            'beds' => 2,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 1,
            'property_name' => 'Brown Roof',
            'near_beach' => 1,
            'accepts_pets' => 0,
            'sleeps' => 3,
            'beds' => 3,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 4,
            'property_name' => 'Black Terrace',
            'near_beach' => 0,
            'accepts_pets' => 1,
            'sleeps' => 5,
            'beds' => 6,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 5,
            'property_name' => 'White Cottage',
            'near_beach' => 0,
            'accepts_pets' => 0,
            'sleeps' => 5,
            'beds' => 5,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 2,
            'property_name' => 'White House',
            'near_beach' => 1,
            'accepts_pets' => 0,
            'sleeps' => 4,
            'beds' => 4,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 5,
            'property_name' => 'Blue Building',
            'near_beach' => 1,
            'accepts_pets' => 1,
            'sleeps' => 2,
            'beds' => 2,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 3,
            'property_name' => 'River Cottage',
            'near_beach' => 0,
            'accepts_pets' => 1,
            'sleeps' => 1,
            'beds' => 1,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 4,
            'property_name' => 'Lake House',
            'near_beach' => 1,
            'accepts_pets' => 0,
            'sleeps' => 3,
            'beds' => 3,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 3,
            'property_name' => 'Blue Ceiling',
            'near_beach' => 1,
            'accepts_pets' => 1,
            'sleeps' => 3,
            'beds' => 5,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 2,
            'property_name' => 'Road Cottage',
            'near_beach' => 0,
            'accepts_pets' => 0,
            'sleeps' => 4,
            'beds' => 4,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 1,
            'property_name' => 'Halfway House',
            'near_beach' => 0,
            'accepts_pets' => 1,
            'sleeps' => 4,
            'beds' => 5,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 2,
            'property_name' => 'Grange Garden',
            'near_beach' => 1,
            'accepts_pets' => 0,
            'sleeps' => 4,
            'beds' => 4,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 3,
            'property_name' => 'Oak Tree',
            'near_beach' => 0,
            'accepts_pets' => 0,
            'sleeps' => 3,
            'beds' => 4,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 4,
            'property_name' => 'Making House',
            'near_beach' => 1,
            'accepts_pets' => 1,
            'sleeps' => 4,
            'beds' => 5,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 5,
            'property_name' => 'Burrow Level',
            'near_beach' => 1,
            'accepts_pets' => 0,
            'sleeps' => 4,
            'beds' => 4,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 4,
            'property_name' => 'Hardnest Shack',
            'near_beach' => 0,
            'accepts_pets' => 1,
            'sleeps' => 5,
            'beds' => 6,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 3,
            'property_name' => 'Sugar Inn',
            'near_beach' => 0,
            'accepts_pets' => 0,
            'sleeps' => 3,
            'beds' => 3,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 2,
            'property_name' => 'Calicony Beds',
            'near_beach' => 1,
            'accepts_pets' => 1,
            'sleeps' => 4,
            'beds' => 5,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 1,
            'property_name' => 'Brave Let',
            'near_beach' => 1,
            'accepts_pets' => 0,
            'sleeps' => 6,
            'beds' => 6,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 2,
            'property_name' => 'Harrow Cottage',
            'near_beach' => 0,
            'accepts_pets' => 1,
            'sleeps' => 6,
            'beds' => 8,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 3,
            'property_name' => 'Hire This Guy',
            'near_beach' => 0,
            'accepts_pets' => 1,
            'sleeps' => 3,
            'beds' => 5,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'location_id' => 4,
            'property_name' => 'Green Cottage',
            'near_beach' => 1,
            'accepts_pets' => 0,
            'sleeps' => 4,
            'beds' => 2,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]
        
        ]);
    }
}